config/routes.rb
Bankr::Application.routes.draw do
  root :to=> "dashboard#index"

  devise_for :users

	resources :accounts do
		resources :categories
		resources :transactions
	end
	
	resources :categories	do
		resources :category_matchers
	end

end

app/models/account.rb
class Account < ActiveRecord::Base
	belongs_to :user

	validates :user_id, :presence => true, :numericality => true
	validates :name, :presence => true
	validates :bank_name, :presence => true
	#validates :balance, :presence => true, :numericality => true
	
	has_many :transactions
	has_many :categories



end

app/models/category.rb
class Category < ActiveRecord::Base

	has_many :transactions
	has_many :category_matchers
	belongs_to :account
	
	
	validates :name, :presence => true

end

app/models/category_matcher.rb
class CategoryMatcher < ActiveRecord::Base
	belongs_to :category
end

app/models/category_type.rb
class CategoryType < ActiveRecord::Base
	
	has_many :categories
	belongs_to :account
	
	validates :name, :presence => true
	
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base

	belongs_to :account
	belongs_to :category

	before_save :set_transaction_type, :match_category
	
	after_save :update_category_matchers

	validates :account_id, :presence => true, :numericality => true
	validates :amount, :presence => true, :numericality => true
	validates :posted_at, :presence => true

	scope :credits, where(:transaction_type => 'CREDIT')
	scope :debits, where(:transaction_type => 'DEBIT')
	scope :last_month, lambda { where('posted_at >= ? and posted_at <= ?', Date.today.months_ago(1).beginning_of_month, Date.today.months_ago(1).end_of_month) }
	
	scope :for_month, lambda { |ago| where('posted_at >= ? and posted_at <= ?', Date.today.months_ago(ago).beginning_of_month, Date.today.months_ago(ago).end_of_month) }
	
	default_scope order('posted_at DESC')

	private

	def set_transaction_type
		self.transaction_type = (amount > 0) ? 'CREDIT' : 'DEBIT'
	end
	
	def match_category
		matches = CategoryMatcher.where("matcher ILIKE ?", "#{self.name}")
		self.category_id = matches.first.category_id if matches.present?
	end
	
	def update_category_matchers
	  if category
	    @existing_matcher = CategoryMatcher.where("matcher ILIKE ?", "#{self.name}")
  	  unless @existing_matcher.present?
  	    category.category_matchers << CategoryMatcher.new(:matcher => self.name)
  	  end
  	end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :email, :password, :password_confirmation, :remember_me

	has_many :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < InheritedResources::Base
	
	def create
		@account = Account.new(params[:account])
    @account.user_id = current_user.id
		create!
	end
	
	def show
		params[:months_ago] ||= 1
		@account = Account.find(params[:id])
		@transactions = @account.transactions.for_month(params[:months_ago].to_i).includes(:category)
		show!
	end
	
	protected
	
	def begin_of_association_chain
		@current_user
	end
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
	
	def create
		@category = Category.new(params[:category])
    @category.account_id = params[:account_id]
		create!
	end

end

app/controllers/category_matchers_controller.rb
class CategoryMatchersController < InheritedResources::Base
	
	def create
		@category_matcher = CategoryMatcher.new(params[:category_matcher])
    @category_matcher.category_id = params[:category_id]
		create!
	end

end

app/controllers/category_types_controller.rb
class CategoryTypesController < InheritedResources::Base
	

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	before_filter :authenticate_user!

	def index
		@accounts = current_user.accounts
	end

end

app/controllers/transactions_controller.rb
class TransactionsController < InheritedResources::Base
	
	def index
		@account = Account.find(params[:account_id])
		@transactions = @account.transactions.includes(:category).last_month
		if params[:type] == 'credits'
			@transactions = @transactions.credits
		elsif params[:type] == 'debits'
			@transactions = @transactions.debits
		end
	end
	
	def edit
		@account = Account.find(params[:account_id])
		edit!
	end
	
	def update
		@account = Account.find(params[:account_id])
		update!{account_transactions_path(@account)}
	end

	protected
	
	def begin_of_association_chain
		@current_user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/accounts/new.html.erb
<% semantic_form_for @account do |form| %>
	<%= form.inputs :name, :bank_name %>
	<%= form.buttons %>
<% end %>

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

<%= link_to 'Categories', account_categories_path(@account) %> 
<%= link_to 'Transactions', account_transactions_path(@account) %>
<%= link_to 'Import', new_account_transaction_path(@account) %>

<h2>Summary</h2>
<table>
	<tr>
		<td><%= link_to 'Credits', account_transactions_path(@account, :type => 'credits') %></td>
		<td><%= number_to_currency @transactions.credits.sum(:amount) %></td>
	</tr>
	<tr>
		<td><%= link_to 'Debits', account_transactions_path(@account, :type => 'debits') %></td>
		<td><%= number_to_currency @transactions.debits.sum(:amount) %></td>
	</tr>
</table>

<h2>Spending Breakdown</h2>
<table>
	<thead>
		<th>Category</th>
		<th>Amount</th>
		<th>Month Previous</th>
	</thead>
<% @transactions.debits.group_by(&:category).each do |category, transactions| %>
	<tr>
		<td><%= category ? category.name : 'Uncategorised' %></td>
		<td><%= number_to_currency transactions.sum(&:amount) %></td>
		<td><%= category.transactions.for_month(2).sum(:amount) if category %></td>
	</tr>
<% end %>
<tr>
	<td></td>
	<td><%= number_to_currency @transactions.debits.sum(:amount) %></td>
</tr>
 </table>

app/views/categories/index.html.erb
<h1>Labels</h1>

<%= link_to 'New', new_account_category_path(@account) %>

<table>
	<tr>
		<th>Label</th>
		<th>Amount</th>
	</tr>
	<% @categories.each do |category| %>
		<tr>
			<td><%= link_to category.name, category_path(category) %></td>
			<td><%= category.transactions.sum(:amount).to_i %></td>
		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<% semantic_form_for ['account', @category] do |form| %>
	<%= form.inputs :name %>
	<%= form.buttons %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>
<h2>Label Matchers</h2>

<%= link_to 'New', new_category_category_matcher_path(@category) %>

<ul>
<% @category.category_matchers.each do |matcher| %>
	<li><%= link_to matcher.matcher %></li>
<% end %>
</ul>

app/views/category_matchers/new.html.erb
<% semantic_form_for ['category', @category_matcher] do |form| %>
	<%= form.inputs :matcher %>
	<%= form.buttons %>
<% end %>

app/views/dashboard/index.html.erb
<h1>Hi, <%= @current_user.email %>!</h1>

<% if @accounts %>
	<ul>
	<% @accounts.each do |account| %>
		<li><%= link_to account.name, account_path(account) %>
	<% end %>
	</ul>
<% else %>

<% end %>

<%= link_to 'Add Account', new_account_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bankr</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

	<% if current_user %>
		<ul>
			<li><%= link_to 'Logout', destroy_user_session_path %>
		</ul>
	<% end %>

  <%= yield %>

</body>
</html>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>


<% semantic_form_for [@account, @transaction] do |form| %>
	<%= form.inputs %>
	<%= form.buttons %>
<% end %>

app/views/transactions/index.html.erb
<h1><%= link_to @account.name, account_path(@account) %></h1>

<%= link_to 'Categories', account_categories_path(@account) %> 
<%= link_to 'Transactions', account_transactions_path(@account) %>
<%= link_to 'Import', new_account_transaction_path(@account) %>

<table>
	<tr>
		<td>Date</td>
		<td></td>
		<td>Category</td>
		<td>Amount</td>
		<td></td>
	</td>
<% @transactions.each do |transaction| %>
	<tr>
		<td><%= transaction.posted_at%></td>
		<td><%= transaction.name %></td>
		<td><%= transaction.category.name if transaction.category %>
		<td><%= transaction.amount %></td>
		<td><%= link_to 'edit', edit_account_transaction_path(@account, transaction) %></td>
	</tr>
<% end %>
</table>

app/views/transactions/new.html.erb
<h1>Importing New Transactions</h1>